[theme]

# Primary accent for interactive elements
primaryColor = '#BEF992'

# Background color for the main content area
backgroundColor = '#343434'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#364735'

# Color used for almost all text
textColor = '#FFFFFF'

